import { ChangeDetectionStrategy, Component, DestroyRef, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';

import { AdminCategory } from '../../models/admin.models';
import { AdminService } from '../../services/admin.service';
import { extractApiError } from '../../services/auth.service';
import { ToastService } from '../../services/toast.service';

@Component({
  selector: 'app-admin-categories',
  imports: [ReactiveFormsModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="flex items-center justify-between"><p class="text-[#6a4425]"><strong>{{ categories().length }}</strong> {{ plural() }}</p><button type="button" class="rounded-lg bg-[#f5b800] px-4 py-2.5 font-bold" (click)="open()">+ Додати категорію</button></div>
    @if (error()) { <div class="mt-5 rounded-lg bg-[#f5dcd3] p-4">{{ error() }} <button type="button" class="underline" (click)="load()">Спробувати ще</button></div> } @else if (loading()) { <div class="mt-5 h-64 animate-pulse rounded-xl bg-[#f5ecd8]"></div> } @else if (!categories().length) { <div class="mt-5 rounded-xl border border-[#dac7a2] bg-white p-10 text-center">Категорій ще немає. <button type="button" class="font-bold underline" (click)="open()">+ Додати категорію</button></div> } @else { <div class="mt-5 overflow-hidden rounded-xl border border-[#dac7a2] bg-white"><div class="grid grid-cols-[1fr_130px_90px_120px] gap-3 bg-[#f5ecd8] px-5 py-3 text-xs font-bold uppercase"><span>Назва</span><span>URL (slug)</span><span>Товарів</span><span class="text-right">Дії</span></div>@for (category of categories(); track category.id) { <div class="grid grid-cols-[1fr_130px_90px_120px] items-center gap-3 border-t border-[#eadcc0] px-5 py-4"><span class="font-bold">{{ category.name }}</span><span class="truncate text-sm text-[#9c8461]">/{{ category.slug }}</span><span>{{ category.activeProductCount }}</span><div class="flex justify-end gap-2"><button type="button" class="rounded border border-[#c2ab80] px-2 py-1 text-sm" (click)="open(category)">Ред.</button><button type="button" class="rounded border border-[#b23a2e] px-2 py-1 text-sm text-[#b23a2e]" (click)="delete(category)">Видалити</button></div></div> }</div> }
    @if (editing()) { <div class="fixed inset-0 z-40 bg-[#2a1a0d]/45" (click)="close()"></div><aside class="fixed inset-y-0 right-0 z-50 flex w-full max-w-md flex-col bg-white shadow-2xl"><header class="flex items-center justify-between border-b p-6"><h2 class="text-xl font-black">{{ editing()!.id ? 'Редагувати категорію' : 'Нова категорія' }}</h2><button type="button" aria-label="Закрити" class="text-xl" (click)="close()">×</button></header><form class="flex flex-1 flex-col p-6" [formGroup]="form" (ngSubmit)="save()"><label class="text-sm font-bold">Назва категорії<input formControlName="name" class="mt-1 w-full rounded-lg border border-[#c2ab80] p-3 font-normal" /></label>@if (form.controls.name.invalid && (form.controls.name.touched || saving())) { <p class="mt-1 text-xs text-[#b23a2e]">Вкажіть назву категорії.</p> }<p class="mt-5 rounded bg-[#f5ecd8] p-3 text-sm">URL (slug): /catalog?category=<strong>{{ slug() }}</strong></p><label class="mt-5 text-sm font-bold">Опис <span class="font-normal text-[#9c8461]">— необовʼязково</span><textarea formControlName="description" class="mt-1 min-h-28 w-full rounded-lg border border-[#c2ab80] p-3 font-normal"></textarea></label><div class="mt-auto flex gap-3 pt-6"><button type="submit" class="flex-1 rounded-lg bg-[#f5b800] py-3 font-bold disabled:opacity-50" [disabled]="saving()">{{ saving() ? 'Зберігаємо…' : 'Зберегти' }}</button><button type="button" class="rounded-lg border border-[#c2ab80] px-4 py-3 font-bold" (click)="close()">Скасувати</button></div></form></aside> }
  `,
})
export class AdminCategoriesComponent {
  private readonly admin = inject(AdminService); private readonly toast = inject(ToastService); private readonly fb = inject(FormBuilder).nonNullable; private readonly destroyRef = inject(DestroyRef);
  readonly categories = signal<AdminCategory[]>([]); readonly loading = signal(true); readonly error = signal(''); readonly saving = signal(false); readonly editing = signal<AdminCategory | { id: 0 } | null>(null);
  readonly form = this.fb.group({ name: ['', Validators.required], description: [''] }); readonly slug = () => this.form.controls.name.value.toLowerCase().trim().replace(/['’]/g, '').replace(/[^a-zа-яіїєґ0-9]+/gi, '-').replace(/^-|-$/g, '');
  constructor() { this.load(); }
  plural(): string { const n = this.categories().length % 100; const last = n % 10; return n > 10 && n < 20 ? 'категорій' : last === 1 ? 'категорія' : last >= 2 && last <= 4 ? 'категорії' : 'категорій'; }
  load(): void { this.loading.set(true); this.error.set(''); this.admin.getCategories().pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: response => { if (response.success) this.categories.set(response.data); else this.error.set(response.error ?? 'Не вдалося завантажити категорії'); this.loading.set(false); }, error: error => { this.error.set(extractApiError(error, 'Не вдалося завантажити категорії')); this.loading.set(false); } }); }
  open(category?: AdminCategory): void { this.editing.set(category ?? { id: 0 }); this.form.reset({ name: category?.name ?? '', description: category?.description ?? '' }); }
  close(): void { this.editing.set(null); }
  save(): void { this.form.markAllAsTouched(); const current = this.editing(); if (!current || this.form.invalid || this.saving()) return; this.saving.set(true); const payload = { name: this.form.controls.name.value, slug: this.slug(), description: this.form.controls.description.value || null }; const request = current.id ? this.admin.updateCategory(current.id, payload) : this.admin.createCategory(payload); request.pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: response => { this.saving.set(false); if (response.success) { this.toast.success('Категорію збережено'); this.close(); this.load(); } else this.toast.error(response.error ?? 'Не вдалося зберегти категорію'); }, error: error => { this.saving.set(false); this.toast.error(extractApiError(error, 'Не вдалося зберегти категорію')); } }); }
  delete(category: AdminCategory): void { if (!confirm(`Видалити категорію «${category.name}»?`)) return; this.admin.deleteCategory(category.id).pipe(takeUntilDestroyed(this.destroyRef)).subscribe({ next: response => { if (response.success) { this.toast.success('Категорію видалено'); this.load(); } else this.toast.error(response.error ?? 'Не вдалося видалити категорію'); }, error: error => this.toast.error(extractApiError(error, 'Не вдалося видалити категорію')) }); }
}
